.TH ridgeclassexport 1 "April 23, 2013" "Surrey Space Centre" 1.0
.SH NAME
ridgeclassexport - Split classified ridge data into separate files.
.SH SYNOPSIS
.B ridgeclassexport
\fIRDG_FILE\fR \fICLASSA_FILE\fR \fICLASSB_FILE\fR

.SH DESCRIPTION
.PP
\fBridgeclassexport\fR splits a ridge data file containing classification
metadata into per-class files.  It supports binary classified data.
Classified ridge data is read from \fIRDG_FILE\fR, and written to
\fICLASSA_FILE\fR and \fICLASSB_FILE\fR.

.SH AUTHOR
Written by Peter TB Brett, Surrey Space Centre, University of Surrey,
UK.

.SH COPYRIGHT
.nf
Copyright \(co 2010-2013 Peter TB Brett <p.brett@surrey.ac.uk>.
License GPLv3+: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>.
.PP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

.SH SEE ALSO
\fBridgetool\fR(1), \fBridgeclassstat\fR(1).
